# Copyright (c) 2019 Anton Semjonov
# Licensed under the MIT License

# ---------- build binary ----------

# golang base image
FROM golang:1.11-alpine as builder

# fetch sources
RUN apk add --no-cache git binutils \
  && go get -u github.com/mholt/caddy \
  && go get -u github.com/caddyserver/builds \
  && go get -u github.com/jung-kurt/caddy-cgi

# apply patches
RUN cd "$GOPATH/src/github.com/mholt/caddy/caddy" \
  && sed -i 's/\(enableTelemetry = \)true/\1false/wI' caddymain/run.go \
  && sed -i $'/caddy\/caddyhttp/a\ \t_ "github.com/jung-kurt/caddy-cgi"' caddymain/run.go

# build binary
RUN cd "$GOPATH/src/github.com/mholt/caddy/caddy" \
  && go run build.go \
  && strip --strip-debug --strip-unneeded caddy \
  && mv caddy /caddy

# ---------- runtime image ----------

# use python base image
FROM python:3-alpine

# metadata
LABEL maintainer="Anton Semjonov <anton@semjonov.de>"
LABEL license="MIT License"

# change directory to webroot
WORKDIR /srv/www

# copy binary and prepare sample config
COPY --from=builder /caddy /caddy
COPY caddyfile /caddyfile
COPY hello.py /srv/www/hello.py

# set entrypoint
ENTRYPOINT ["/caddy"]
CMD ["-conf", "/caddyfile"]
